### ISSUE TITLE
Document examples and their purpose

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#114]
Right now, the various examples serve different purposes, and it not clear (not documented at all?) what their respective purposes is. For example, I always thought that `simple_trixi_controller` was the simplest of examples, but it turns out you need to compile it with MPI enabled.

Maybe we could add a small overview section to the docs that explains which "features" are tested in each of the examples?

**Comment by bgeihe** [comment]
Yes, this needs cleanup.

Since we have our testing setup, we do not need the examples for testing purposes anymore. Still we obviously want to demonstrate how to use libtrixi, so we need examples and we need to make sure that they work (CI).

To keep CI load low, we could demonstrate all functionality in one big example, which does not seem to be a good idea.

If we can ignore CI load, we could have the following

- (Truly) simple trixi controller (without MPI)
- simple trixi controller (with MPI)
- trixi controller with data access
- trixi controller with t8code

and add this description to the docs.

**Comment by sloede** [comment]
Sounds good to me! And we should have these examples available in C and Fortran.
