### ISSUE TITLE
LibTrixi.jl does not pull in latest Trixi.jl version

### ISSUE THREAD

**Issue by benegee** [trixi-framework/libtrixi#190]
When setting up libtrixi using `libtrixi-init-julia`, not the latest Trixi.jl version is installed, but v0.5.36. See e.g. https://github.com/trixi-framework/libtrixi/actions/runs/8964091186/job/24615337557#step:16:805

In the` [compat]` section we have
`Trixi = "0.5.29, 0.6, 0.7"`
and indeed Trixi can be upgraded afterwards without problems.  

I tried to reproduce this with a LibTrixi.jl dummy package, which only has Trixi.jl as a dependency. I started with a fresh Julia project and `]dev <path>/LibTrixi.jl`, which resulted in
```
Status `~/install/libtrixi-julia-test/Manifest.toml`
...
⌃ [a7f1ee26] Trixi v0.6.5 (<v0.7.13)
```
(The same happens with the real LibTrixi.jl package, i.e. `]add LibTrixi`)

As indicated, Trixi.jl can be updated. However `DiffEqBase` is then downgraded:
```
⌅ [2b5f629d] ↓ DiffEqBase v6.145.2 ⇒ v6.143.0
```

Is this the reason why Trixi v0.6.5 was chosen in the first place? (The `DiffEqBase` compat entry for Trixi.jl was introduced in v0.6.6)

Starting again with  a fresh project and doing `pkg> add Trixi` in the first place directly installs ` [a7f1ee26] + Trixi v0.7.13`, and `]dev <path>/LibTrixi.jl` afterwards succeeds without downgrading Trixi.jl.
So, should we just swap the order of installation?

**Comment by sloede** [comment]
I think the problem might be that we are requiring an older version of OrdinaryDiffEq (or DiffEqBase etc.) in Trixi.jl. Generally, I'd say it does not make sense to swap the order, since it could mean we might not get the latest LibTrixi.jl version. However, since this is particularly annoying, _and_ Trixi.jl _is_ the main package, can you please try to swap orders to see if it fixes things?

**Comment by benegee** [comment]
It does!
