### ISSUE TITLE
Check installation of libtrixi?

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#23]
The current cmake setup is able to `make install` the libtrixi shared object and include files. 

Should we keep providing this? 

Missing once #20 and #21 are deployed:
- [x] `LibTrixi.jl` (just copy it?)

**Comment by sloede** [comment]
I wonder if we should maybe add more of the stuff that is currently run in the init script to the build step/install step. For example, the MPI library to be used by Julia should be the exact same as it used for compiling libtrixi, thus it would be reasonable to create the `LocalPreferences.toml` file already during build/install time and not later. That way, we could also include p4est in the build part, have it link against one of our example programs, and then write all necessary information to the `LocalPreferences.toml` file as well.

This would avoid/reduce the probability for misconfigurations, where libtrixi.so is built with a different library than is later used by LibTrixi.jl.

**Comment by sloede** [comment]
LibTrixi.jl and the init script are now also installed:
https://github.com/trixi-framework/libtrixi/blob/a187024961b46f36eebec912f14de092b1ccd6f6/CMakeLists.txt#L71-L72
Thus for I now I suggest to keep the installation option, since it is much cleaner than the build directory, and with #24 I think we do not need neither build dir nor repo to use libtrixi.
