### ISSUE TITLE
Figure out and document how to install Julia packages and how to select the correct Julia project

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#3]
Something I do not get straight: When we follow the "Julia-REPL-like" approach to call everything else, we need a Julia runtime environment. Currently  (#1) the system environment is used, but in the end, when we need to switch MPI and so on, we need a dedicated one. 

1. Where should this Julia project reside? In the source tree? At a user specified location? Auto-generated by  `cmake install`?
2. A user will typically execute his code from somewhere else. How does libtrixi know the location of the project to activate. It cannot be hard-coded. Should it be passed to `trixi_initialize()`?

**Comment by sloede** [comment]
These are very good points. 
> Where should this Julia project reside? In the source tree? At a user specified location? Auto-generated by cmake install?

I believe it must live at a user-specified location. Auto-generation by CMake is IMHO not super useful, since it assumes  that the user will build a separate libtrixi for each different project configuration. Also, we might need to load additional Julia code (e.g., the `LibTrixi.jl` project that I started to work on in #2).

For now, I would thus just document in the README.me which files a user would have to copy to a "runtime" directory and how to modify them.

> A user will typically execute his code from somewhere else. How does libtrixi know the location of the project to activate. It cannot be hard-coded. Should it be passed to trixi_initialize()?

Yes. I think ultimately this will be the most user-friendly option. A user should just be able to pass the location of the Julia project as an argument to their program (e.g., using Fortran namelists), which then passes it to `trixi_initialize`.

**Comment by bgeihe** [comment]
For now the relative path to `Libtrixi.jl` is hard-coded.

We could allow to specify a custom path, but will have to make sure or at least document how the runtime directory has to be set up.

**Comment by sloede** [comment]
> For now the relative path to `Libtrixi.jl` is hard-coded.
> 
> We could allow to specify a custom path, but will have to make sure or at least document how the runtime directory has to be set up.

This will be partially resolved by #16, which introduces the ability to provide custom paths. Note that the documentation part is still missing.
