### ISSUE TITLE
Keep VERSION consistent to LibTrixi.jl/Project.toml

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#62]
Addendum to #56 : Do we need and can we make sure that the versions in file `VERSION`  and `LibTrixi.jl/Project.toml` agree?

**Comment by sloede** [comment]
I've been thinking about this a little more. One could consider that LibTrixi.jl is really the main software product here, and that everything else is just a means to use it, ie, by providing C and Fortran bindings. In that case, we could remove the `VERSION` file and have the existing `trixi_version_xxx` functions call corresponding functions in LibTrixi.jl (as opposed to having hard coded return values as they do now).

This would also resolve #57, since we could just rely on JuliaRegistrator and TagBot to do the release process for us.

**Comment by bgeihe** [comment]
Sounds reasonable, fine with me.
