### ISSUE TITLE
Improve C interface tests

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#73]
Right now our CI runs two examples (each in C and Fortran) and checks whether they finish without errors.

Do we want more?

- Unit tests? 
- Tests with random or perturbed data?
- Third party testing framework?

**Comment by sloede** [comment]
IMHO, we probably want to keep our testing infrastructure as simple as possible. That is, it should be simple to add new tests (otherwise they will not be created) and simple to identify bugs (otherwise they will not be fixed).

At the moment, I am not 100% sure what our setup should/can look like. But from our experience with Trixi.jl, I'd say that we'll probably have more or less "integrated unit tests", e.g., something similar to our current controller examples but where we verify the result of each API call. I am not sure if we need a third-party testing framework for this, or if we are better off by rolling our own.

What I don't think we need is testing with random/perturbed data. Most of the functionality we want to test is regarding the interface, and there a correct answer is usually easy to detect. We do not need, e.g., to verify the results of simulations (since this is done already in Trixi.jl), but only things like transferring data to-and-fro, and that all API calls work as expected.

Does this help?

**Comment by bgeihe** [comment]
Yes, thanks for your thoughts on this!

**Comment by sloede** [comment]
There are some Fortran unit testing frameworks, as listed, e.g., [here](https://github.com/Beliavsky/Fortran-code-on-GitHub/blob/main/README.md#unit-testing) or [here](https://fortranwiki.org/fortran/show/Unit+testing+frameworks). However, I don't know any of them, so I can't give good recommendations.

We could also try to roll our own, e.g., to essentially code up 2-3 examples as tests, where we use the interface functions and verify the return values/functionality. Since we test the "external language <-> Julia" interaction already with the C code, we really only have to verify that the Fortran layer does not change anything while interacting with C, so I think it would be feasible to do it using manually coded tests.
