### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by bgeihe** [trixi-framework/libtrixi#77]
Files / folders:
- [x] `trixi.h` is the public interface definition, it should not change
- [x] ~~Organize C-API implementation according to purpose (`setup.c`, `version.c`, `control.c`, `data.c`)~~
- [x] C-API (`api.c`), Fortran-API (`api.f90`), Julia-API (`api_c.jl`, `api_jl.jl`) remain in single files
- [x] ~~function pointers must be made available to multiple c-files. Move them to `function_pointers.h/c`?~~
- [x] General purpose routines like `print_and_die` are moved to `auxiliary.h/c`

Code:
- [x] all interface routines should start with `trixi_`
- [x] `trixi_version_*` is replaced by `trixi_version_library_*` to be consistent with `trixi_version_julia*`
- [x] `julia_eval_string` is renamed to `trixi_eval_julia` and used in examples

**Comment by sloede** [comment]
Some thoughts:

> function pointers must be made available to multiple c-files. Move them to `function_pointers.h/c`?

Sounds good to me.

> There are more general purpose routines like `print_and_die` ... move them to `internal.h/c`, `general.h/c`, ...?

`internal`/`general` are imho too general (everything not an API is `internal`, and `general`... well, it's in the name). Maybe `auxiliary.h/c`?

> Organize api implementation according to purpose (version, simulation control, data access, ...)

Sounds good to me.

> Subfolders `api_c` and `api_fortran` ?

I wouldn't start to think about subfolders unless we exceed 20 files.

> Use the some folder structure and sorting beneath `LibTrixi.jl/src`?

Sounds nice on first thought, but then might be arbitrarily restrictive. Maybe `api.c` and `api_c.jl` are already named similarly enough, the rest is not as important imho.

> all interface routines should start with `trixi_`

Yes!

> isn't `trixi_version` misleading? Maybe use `trixi_libtrixi_version`, although it is quiet long? 

I agree, this seems weird to me as well. Maybe `trixi_library_version`?

**Comment by bgeihe** [comment]
I updated the description to reflect the current state and my thoughts? Could you have another look @sloede ?

**Comment by sloede** [comment]
>     * [ ]  Split Fortran interface specification accordingly in multiple `*.f90` files?

Did you keep the C API in one file? If it is not more than 500 lines, that's what I would probably do. If the C API is split up, I would either split up the Fortran API using the same structure/filenames or keep them in one file. Since the Fortran bindings are mostly interface definitions and should be part of a single module, using a single file is probably by far the easiest option.

>     * [ ]  Split Julia interface implementation accordingly? **NO**

No. As I said, I'd probably also leave the C API in one file, unless it gets out of hand.

>     * [ ]  isn't `trixi_version` misleading?
>       
>       * Maybe use `trixi_libtrixi_version`, although it is quiet long?
>       * `trixi_library_version`?
>       * also `trixi_library_version_major`, ...?
>       * `trixi_version_library` to be consistent with `trixi_version_julia`?

This is slowly getting to the point of being just 🚲🛖ing. IMHO `trixi_libtrixi_version` is not a good choice, since someone who does not care about the Julia part will not immediately understand the meaning of the double "trixi".

The most consistent one would be, I agree, `trixi_version_library`/`trixi_version_library_major` etc. and `trixi_version_julia`/`trixi_version_julia_extended`. But the other option is fine too, really, anyone using these will probably look them up once, use them, and then forget about them anyways :-)
 
>     * [ ]  remove `julia_eval_string` from interface to not let users execute arbitrary julia code?

This might make for a nice debugging tool. I'd therefore keep it, rename it consistently to something like `trixi_eval_julia`, and provide a Fortran binding for it.
