### ISSUE TITLE
Code coverage not tracking C header files

### ISSUE THREAD

**Issue by sloede** [trixi-framework/libtrixi#94]
When looking at the current coverage builds, it seems like neither [Coveralls](https://coveralls.io/builds/62319576) nor [Codecov](https://app.codecov.io/gh/trixi-framework/libtrixi/commit/b4f6decebedbdbbf30a26ac88f74cc28ad27dde5/tree?search=&displayType=list) are trackingn our C header files. Is this intentional or an oversight @bgeihe?

To be sure, as long as we do not have inline implementations of functions that exist only in headers, everything of relevant functionality should be tested. However, I am wondering if we should include the header files nonetheless.

**Comment by bgeihe** [comment]
Good observation! 

As far as I remember, since I started looking into the coverage reports, I did not see any header files there.
(Except `julia.h` which has some inlined code though)
I did not intentionally exclude header files either. So maybe it is just because there is no executable code inside our headers? (similar to the Fortran interface definition)

**Comment by sloede** [comment]
Hm, ok. Then I guess it's ok :-). Thanks for the test!
